name: CI

on: [push]

jobs:
  cv_job:
    runs-on: ubuntu-latest
    name: A job to compile cv via pdflatex
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run action
        uses: ./
        id: run_cv
